apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2019-12-06T22:06:54Z"
  generation: 4
  labels:
    app: worker-server
  name: worker-server
  namespace: default
  resourceVersion: "721127"
  selfLink: /apis/apps/v1/namespaces/default/deployments/worker-server
  uid: b6462438-1874-11ea-8f0d-42010a8a0009
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-server
    spec:
      containers:
      - image: gcr.io/csci5253/worker-server:v3
        imagePullPolicy: IfNotPresent
        name: worker-server
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-k80
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
